### ISSUE TITLE
Check for signed-off-by doesn't ignore comments

### ISSUE THREAD

**Issue by iamniting** [wagoid/commitlint-github-action#187]
Same as https://github.com/conventional-changelog/commitlint/issues/1809
Fix: https://github.com/conventional-changelog/commitlint/pull/2098

Can we get this change in the action? I am also getting the same issue.

![Screenshot from 2021-07-01 14-24-04](https://user-images.githubusercontent.com/22993933/124096245-08975c00-da78-11eb-8dee-5aa0f2ede177.png)

**Comment by wagoid** [comment]
Hey @iamniting! Issue is now fixed on v4 👍

**Comment by iamniting** [comment]
Cool thanks @wagoid

**Comment by iamniting** [comment]
@wagoid It is still failing.
![Screenshot from 2021-07-15 18-38-43](https://user-images.githubusercontent.com/22993933/125794075-bf54efde-7145-49dc-a34e-7736ac828156.png)

result link https://github.com/iamniting/odf-operator/runs/3076882169?check_suite_focus=true

**Comment by wagoid** [comment]
Interesting, I'm up to date with commitlint packages but it still fails. Also, I've not tested this behavior [completely](https://github.com/wagoid/commitlint-github-action/blob/master/src/action.test.js#L557-L577)🤦‍♂️. I just tested that it would not break with the signed off message, but didn't add a test for a config file that requires `signed-off-by` rule.

Will have a look and get back to you 👍

**Comment by wagoid** [comment]
@iamniting Now this should be completely fixed! 💪

**Comment by iamniting** [comment]
Thanks @wagoid It is fixed now.
